package com.yigitcanture.convertor.util;

public class StringConstants {
	
	/**
	 * To Generate copy rights
	 */
	public static final String COMMENT = "//";
	public static final String COPY_RIGHTS = "//  Created by "; 
	public static final String COPY_RIGHTS_END = "\n//  Copyright (c) 2016 MacBook. All rights reserved.\n";
	public static final String GENERATED = "//  Generated by ";
	public static final String GENERATED_END = "\n";  

	/**
	 * to find java props.
	 */
	public static final String PRIVATE_PATTERN = "private[a-zA-Z0-9_ <>,]*;?";
	public static final String PATTERN_CATCH_PROPERTY = "private ([a-zA-Z\\(<,? >\\)]+)\\s([a-zA-Z0-9_ ]+)";
	public static final String PATTERN_MAP = "<([a-zA-Z0-9_]+), ?([a-zA-Z0-9_]+)>";
	public static final String PATTERN_LIST = "<([a-zA-Z0-9_]+)>";
	
	private StringConstants() {
	}
}
