//
//  SampleObject2.h
//  Example Project
//  Created by Yigit Can Ture
//  Copyright (c) 2016 MacBook. All rights reserved.
//  Generated by Yigit Can Ture
//



@interface SampleObject2

@property (nonatomic,strong) NSNumber* longObj;

@end