//
//  SampleObject.h
//  Example Project
//  Created by Yigit Can Ture
//  Copyright (c) 2016 MacBook. All rights reserved.
//  Generated by Yigit Can Ture
//

#import "EmptyObject.h"


@interface SampleObject

@property (nonatomic,assign) NSDecimal bigDecimal;
@property (nonatomic,strong) NSNumber* bigInteger;
@property (nonatomic,strong) NSString* name;
@property (nonatomic,strong) NSDate* date;
@property (nonatomic,assign) long longP;
@property (nonatomic,strong) NSMutableArray* list;
@property (nonatomic,strong) NSMutableDictionary* hashMap;
@property (nonatomic,assign) short shortP;
@property (nonatomic,assign) BOOL booleanObj;
@property (nonatomic,assign) BOOL bool;
@property (nonatomic,strong) EmptyObject* emptyObject;

@end