//
//  SampleObject.m
//  Example Project
//  Created by Yigit Can Ture
//  Copyright (c) 2016 MacBook. All rights reserved.
//  Generated by Yigit Can Ture
//

#import "SampleObject.h" 

@implementation SampleObject


@end